<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Shell Script (interactive)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\$|&gt;) </string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>interactive.prompt.shell</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^.+$</string>
			<key>name</key>
			<string>interactive.output.shell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.interactive.shell</string>
	<key>uuid</key>
	<string>c81eaa29-76b7-4ed2-a611-846d6563ef74</string>
</dict>
</plist>
